language: c

os: linux

dist: bionic

compiler: clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main
        key_url: https://apt.llvm.org/llvm-snapshot.gpg.key
    packages:
      - llvm-10-dev
      - libclang-10-dev
      - libx11-dev
      - libcairo2-dev
      - libjson-c-dev

script:
  - make
